apiVersion: v1
kind: ServiceAccount
metadata:
  name: xray-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xray-admin
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["xray-users"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["xray"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xray-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xray-admin
subjects:
  - kind: ServiceAccount
    name: xray-admin
